# Generated by Django 3.1.3 on 2021-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле заповнюється автоматично. Повинно бути унікальним', unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='назва новини. Макс. довжина 200 символів')),
                ('subtitle', models.CharField(blank=True, help_text='Не обов\'язково заповнювати', max_length=300, verbose_name='підзаголовок. Макс. довжина 300 символів')),
                ('image', models.ImageField(help_text='Головне зображення, яке виводиться в мініатюрі та шапці лендінгу', upload_to='news/%Y-%m-%d/', verbose_name='зображення')),
                ('text', models.TextField(verbose_name='текст новини')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='дата додавання новини')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата оновлення новини')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано та показано на сайті')),
            ],
            options={
                'verbose_name': 'новина',
                'verbose_name_plural': 'новини',
                'ordering': ['-update_date', '-adding_date'],
            },
        ),
    ]
