# Generated by Django 3.1.3 on 2020-12-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'вариант участия', 'verbose_name_plural': 'варианты участия'},
        ),
    ]
