# Generated by Django 3.1.3 on 2021-02-21 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0002_auto_20201216_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location_image',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='students',
        ),
        migrations.AddField(
            model_name='workshop',
            name='location_latitude',
            field=models.CharField(help_text='Например: 47.84353679239588', max_length=100, null=True, verbose_name='Широта координат места проведения'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='location_longitude',
            field=models.CharField(help_text='Например: 35.13022046189983', max_length=100, null=True, verbose_name='Долгота координат места проведения'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='location_title',
            field=models.CharField(help_text='Адрес места проведения Макс. длина 200 символов', max_length=200, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Занятие началось'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(help_text='Макс. длина 200 символов', max_length=200, verbose_name='Краткое описание занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='starting_date',
            field=models.DateTimeField(verbose_name='Время и дата начала занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Макс. длина 150 символов', max_length=150, verbose_name='Название занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='workshop',
            field=models.ForeignKey(help_text='К какому семинару относится занятие', on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Семинар'),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(help_text='Макс. длина 300 символов', max_length=300, verbose_name='Описание варианта участия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Введите целое число без дробной части', max_digits=5, verbose_name='Стоимость варианта участия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(help_text='Название варианта участия. Макс. длина 150 символов', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='option',
            name='workshop',
            field=models.ForeignKey(help_text='К какому семинару относится.', on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Семинар'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='adding_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='Описание семинара'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description_image',
            field=models.ImageField(upload_to='workshops/%Y-%m-%d/', verbose_name='Картинка к описанию'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='header_image',
            field=models.ImageField(help_text='Главное изображение, которое выводится в шапке лендинга', upload_to='workshops/%Y-%m-%d/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован на сайте'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='is_started',
            field=models.BooleanField(default=False, help_text='Если начат, желательно снять галочку с "Опубликован на сайте", чтобы во время его проведения семинар не показывался на сайте, а люди не могли записаться', verbose_name='Семинар начат'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(help_text='Поле автозаполняемо. Должно быть уникально', unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='starting_date',
            field=models.DateField(help_text='Дата начала семинара', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subtitle',
            field=models.CharField(help_text='Макс. длина 250 символов', max_length=250, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(help_text='Название семинара. Служит заголовком на лендинге. Если семинары по этой теме уже проводились, желательно, чтобы было в едином стиле с предыдущими. Макс. длина 200 символов', max_length=200, verbose_name='Название семинара'),
        ),
        migrations.CreateModel(
            name='WorkshopPromocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Набор символов длиной до 20 знаков', max_length=20, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(help_text='Процент скидки, которую предоставляет промокод. Нужно ввести целое число (без символа процента). Минимальное значение - 0, максимальное - 100', verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Промокод активен и действует')),
                ('workshops', models.ManyToManyField(to='workshops.Workshop', verbose_name='На какие семинары распространяется промокод')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'Отменен'), ('wait_paid', 'Ожидается оплата'), ('paid', 'Оплачен')], max_length=30, verbose_name='Статус заказа')),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма покупки')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки курса')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.option', verbose_name='Выбранный вариант участия')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshoppromocode')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshop', verbose_name='Какой курс был приобретен')),
            ],
        ),
    ]
