# Generated by Django 3.1.3 on 2021-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20210222_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshoporder',
            options={'ordering': ['-id'], 'verbose_name': 'заявка на участие', 'verbose_name_plural': 'заявки на участие'},
        ),
        migrations.AlterField(
            model_name='workshoporder',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заявки'),
        ),
    ]
