# Generated by Django 3.1.3 on 2021-02-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20210222_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='location_title',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='location_longitude',
        ),
        migrations.AddField(
            model_name='workshop',
            name='location_image',
            field=models.ImageField(help_text='Скрин с гугл карты места проведения семинара или фото заведения', null=True, upload_to='workshops/%Y-%m-%d/', verbose_name='Изображение локации'),
        ),
        migrations.AlterField(
            model_name='workshoporder',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.workshoppromocode', verbose_name='Промокод'),
        ),
    ]
