# Generated by Django 3.1.3 on 2021-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20210224_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='location',
            field=models.TextField(help_text='Адрес места проведения Макс. длина 200 символов', null=True, verbose_name='Место проведения'),
        ),
    ]
