# Generated by Django 3.1.3 on 2020-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='имя')),
                ('patronym', models.CharField(blank=True, max_length=20, verbose_name='отчество')),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True, verbose_name='e-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y-%m-%d/', verbose_name='фото')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('certificate', models.ImageField(blank=True, upload_to='certificates/%Y/%m/%d/')),
                ('is_certified', models.BooleanField(default=False, verbose_name='сертифицирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='аккаунт активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-register_date'],
            },
        ),
    ]
