# Generated by Django 3.1.3 on 2020-12-09 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле заповнюється автоматично. Повинно бути унікальним.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(help_text='Назва курсу. Служить заголовком на лендінгу. Бажано, щоб була в єдиному стилі з попередніми потоками. Макс. довжина 200 символів.', max_length=200, verbose_name='назва курса')),
                ('subtitle', models.CharField(help_text='Макс. довжина 250 символів.', max_length=250, verbose_name='підзаголовок')),
                ('short_description', models.TextField(help_text='Короткий опис курсу. Макс. довжина 300 символів', max_length=300, verbose_name='короткий опис')),
                ('header_image', models.ImageField(help_text='Головне зображення, яке виводиться в шапці лендингу.', upload_to='courses/%Y-%m-%d/', verbose_name='головне зображення')),
                ('preview_image', models.ImageField(help_text='Зображення, яке відображається в короткому описі курсу в списку всіх курсів.', upload_to='courses/%Y-%m-%d/', verbose_name='анонс картинка')),
                ('starting_date', models.DateField(help_text='дата початку курсу', verbose_name='дата початку')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='дата додавання')),
                ('detail_description', models.TextField(verbose_name='детальний опис курсу')),
                ('detail_image', models.ImageField(upload_to='courses/%Y-%m-%d/', verbose_name='картинка до детального опису курсу')),
                ('results', models.TextField(help_text='Опишіть, які результати отримають учасники курсу після його закінчення.', verbose_name='результат курсу')),
                ('certificate', models.BooleanField(default=False, help_text='Поставте галочку, якщо після закінчення курсу учасникам видається сертифікат', verbose_name='видається сертифікат')),
                ('certificate_image', models.ImageField(blank=True, help_text='Якщо вище ви вказали, що сертифікат видається, обов\'язково необхідно до даного курсу прикріпити його зразок.', null=True, upload_to='courses/%Y-%m-%d/', verbose_name='зображення сертифіката')),
                ('price', models.DecimalField(decimal_places=0, help_text='Введіть ціле число без дробової частини', max_digits=5, verbose_name='вартість')),
                ('is_published', models.BooleanField(default=True, help_text='Курс опублікований на сайті, доступний для придбання та реєстрації. Під час початку курсу не забудьте зняти галочку.', verbose_name='опубліковано')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='учасники курсу')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курси',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='назва категорії')),
                ('short_description', models.CharField(max_length=200, verbose_name='короткий опис')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='студенти')),
            ],
            options={
                'verbose_name': 'суб\'єкт',
                'verbose_name_plural': 'суб\'єктb',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_person', models.ImageField(upload_to='courses/%Y-%m-%d/', verbose_name='картинка до типу персонажа')),
                ('person', models.CharField(max_length=50, verbose_name='тип персонажа')),
                ('person_detail', models.CharField(max_length=100, verbose_name='короткий опис персонажа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'персонаж ЦА',
                'verbose_name_plural': 'персонажі ЦА',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Макс. довжина 150 символів', max_length=150, verbose_name='назва модуля')),
                ('description', models.TextField(blank=True, verbose_name='опис модуля')),
                ('is_published', models.BooleanField(default=True, help_text='Модуль показаний на лендінгу курсу та в кабінеті користувача.', verbose_name='опубліковано')),
                ('is_active', models.BooleanField(default=False, verbose_name='Доступний для проходження.')),
                ('course', models.ForeignKey(help_text='До якого курсу відноситься модуль.', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'модуль',
                'verbose_name_plural': 'модулі',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Макс. довжина 150 символів.', max_length=150, verbose_name='назва уроку')),
                ('description', models.TextField(blank=True, verbose_name='описание урока')),
                ('video', models.URLField(blank=True, help_text='В форматі "http://..."', verbose_name='посилання на відео трансляцію')),
                ('materials', models.URLField(blank=True, verbose_name='посилання на матеріали')),
                ('is_published', models.BooleanField(default=True, help_text='Урок показаний на лендінгу курсу та в кабінеті користувача.', verbose_name='опубликован')),
                ('is_active', models.BooleanField(default=False, verbose_name='доступний для проходження.')),
                ('module', models.ForeignKey(help_text='До якого модуля відноситься урок.', on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='courses.module', verbose_name='модуль')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='До якого суб\'єкта відноситься даний потік курсу.', on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='суб\'єкт'),
        ),
    ]
