# Generated by Django 3.1.3 on 2020-12-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='starting_date',
            field=models.DateField(help_text='Дата начала курса', verbose_name='дата начала'),
        ),
    ]
