# Generated by Django 3.1.3 on 2021-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210203_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_record',
            field=models.URLField(blank=True, help_text='В формате "http://..."', null=True, verbose_name='ссылка на запись урока'),
        ),
    ]
