# Generated by Django 3.1.3 on 2021-02-19 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_lesson_video_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-pk'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['pk'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модулі'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персонаж ЦА', 'verbose_name_plural': 'Персонажі ЦА'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Суб\'єкт', 'verbose_name_plural': 'Суб\'єкти'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='access_period',
            field=models.PositiveIntegerField(help_text='Введіть ціле число, яке буде означати кількість днів', null=True, verbose_name='На скільки днів відкритий доступ до модулів і уроків курсу після покупки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='adding_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.BooleanField(default=False, help_text='Поставте галочку, якщо після закінчення курсу учасникам видається сертифікат', verbose_name='Видається сертифікат'),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_image',
            field=models.ImageField(blank=True, help_text='Якщо вище ви вказали, що сертифікат видається, обов\'язково необхідно до даного курсу прикріпити його зразок', null=True, upload_to='courses/%Y-%m-%d/', verbose_name='Зображення сертифіката'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail_description',
            field=models.TextField(verbose_name='Детальний опис курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail_image',
            field=models.ImageField(upload_to='courses/%Y-%m-%d/', verbose_name='Картинка до детального опису курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='header_image',
            field=models.ImageField(help_text='Головне зображення, яке виводиться в шапці лендингу', upload_to='courses/%Y-%m-%d/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Курс опублікований на сайті, доступний для придбання та реєстрації. Під час початку курсу не забудьте зняти галочку', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_image',
            field=models.ImageField(help_text='Зображення, яке відображається в короткому описі курсу в списку всіх курсів', upload_to='courses/%Y-%m-%d/', verbose_name='Анонс картинка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Введіть ціле число без дробової частини', max_digits=5, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='course',
            name='results',
            field=models.TextField(help_text='Опишіть, які результати отримають учасники курсу після його закінчення', verbose_name='результат курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(help_text='Короткий опис курсу. Макс. довжина 300 символів', max_length=300, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='Поле заповнюється автоматично. Повинно бути унікальним', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='До якого суб\'єкта відноситься даний потік курсу', on_delete=django.db.models.deletion.CASCADE, to='courses.subject', verbose_name='Суб\'єкт'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(help_text='Макс. довжина 250 символів', max_length=250, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Назва курсу. Служить заголовком на лендінгу. Бажано, щоб була в єдиному стилі з попередніми потоками. Макс. довжина 200 символів', max_length=200, verbose_name='Назва курсу'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступний для проходження'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Урок показаний на лендінгу курсу та в кабінеті користувача', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.URLField(blank=True, verbose_name='Посилання на матеріали'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(help_text='До якого модуля відноситься урок', on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Макс. довжина 150 символів', max_length=150, verbose_name='Назва уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, help_text='В форматі "http://..."', verbose_name='Посилання на відео трансляцію'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_record',
            field=models.URLField(blank=True, help_text='В форматі "http://..."', null=True, verbose_name='Посилання на запис уроку'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text='До якого курсу відноситься модуль', on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Доступний для проходження'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Модуль показаний на лендінгу курсу та в кабінеті користувача', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='Макс. довжина 150 символів', max_length=150, verbose_name='Назва модуля'),
        ),
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image_person',
            field=models.ImageField(upload_to='courses/%Y-%m-%d/', verbose_name='Картинка до типу персонажа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.CharField(max_length=50, verbose_name='Тип персонажа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_detail',
            field=models.CharField(max_length=100, verbose_name='Короткий опис персонажа'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Студенти'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва категорії'),
        ),
        migrations.CreateModel(
            name='CoursePromocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Набір символів довжиною до 20 знаків', max_length=20, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(help_text='Відсоток знижки, яку надає промокод. Потрібно ввести ціле число (без символу відсотка). Мінімальне значення - 0, максимальне - 100', verbose_name='Відсоток знижки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Промокод активний і діє')),
                ('courses', models.ManyToManyField(to='courses.Course', verbose_name='На які курси поширюється промокод')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(max_length=30, verbose_name='Унікальний номер замовлення')),
                ('status', models.CharField(choices=[('cancelled', 'Скасовано'), ('wait_paid', 'Очікується оплата'), ('paid', 'Оплачено')], max_length=30, verbose_name='Статус замовлення')),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума покупки')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата придбання курсу')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Який курс був придбаний')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursepromocode', verbose_name='Промокод')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учасник')),
            ],
            options={
                'verbose_name': 'Замовлення курсу',
                'verbose_name_plural': 'Замовлення курсів',
                'ordering': ['-payment_date'],
            },
        ),
    ]
