# Generated by Django 3.1.3 on 2021-02-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210219_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-pk'], 'verbose_name': 'курс', 'verbose_name_plural': 'курси'},
        ),
        migrations.AlterModelOptions(
            name='courseorder',
            options={'ordering': ['-payment_date'], 'verbose_name': 'замовлення курсу', 'verbose_name_plural': 'замовлення курсів'},
        ),
        migrations.AlterModelOptions(
            name='coursepromocode',
            options={'ordering': ['-pk'], 'verbose_name': 'промокод', 'verbose_name_plural': 'промокоди'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['pk'], 'verbose_name': 'модуль', 'verbose_name_plural': 'модулі'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'персонаж ЦА', 'verbose_name_plural': 'персонажі ЦА'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'суб\'єкт', 'verbose_name_plural': 'суб\'єкти'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_published',
        ),
    ]
