# Generated by Django 3.1.3 on 2021-02-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210221_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorder',
            name='promocode',
        ),
    ]
