# Generated by Django 3.1.3 on 2021-02-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courseorder_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorder',
            options={'ordering': ['-payment_date'], 'verbose_name': 'заявка на курс', 'verbose_name_plural': 'заявки на курси'},
        ),
    ]
