# Generated by Django 3.1.3 on 2020-12-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название бренда')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('brand_image', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='логотип бренда')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле автозаполняемо и должно быть уникально.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(max_length=50, verbose_name='название категории')),
                ('subtitle', models.CharField(help_text='выводится на лендинге в шапке. Макс. длина 200 символов.', max_length=200, verbose_name='подзаголовок категории')),
                ('category_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='картинка категории в шапке лендинга')),
                ('preview_category_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='маленькая картинка категории')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например, "Евро" или "Доллар США".', max_length=50, verbose_name='название валюты')),
                ('exchange', models.DecimalField(blank=True, decimal_places=2, help_text='Введите дробное число с двумя цифрами после точки (не запятой).', max_digits=5, null=True, verbose_name='курс по отношению к гривне')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Поле автоматически заполняется в момент последнего сохранения.', verbose_name='когда обновлялся курс')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле автозаполняемо и должно быть уникально.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='название товара')),
                ('short_description', models.CharField(help_text='Макс. длина 300 символов.', max_length=300, verbose_name='краткое описание товара')),
                ('description', models.TextField(verbose_name='полное описание товара')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='стоимость в валюте')),
                ('new_product', models.BooleanField(blank=True, default=False, verbose_name='новинка')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='больше, чем нынешняя', verbose_name='старая цена')),
                ('header_image', models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='главная картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 1')),
                ('image_2', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 2')),
                ('image_3', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 3')),
                ('image_4', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 4')),
                ('image_5', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 5')),
                ('image_6', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 6')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='опубликовано')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='фирма-производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория')),
                ('currency', models.ForeignKey(help_text='При выводе для пользователя будет автоматически пересчитано в гривну.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='в какой валюте стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
