# Generated by Django 3.1.3 on 2020-12-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='назва бренду')),
                ('country', models.CharField(max_length=50, verbose_name='країна')),
                ('brand_image', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='логотип бренду')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренди',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле заповнюється автоматично і має бути унікальним.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(max_length=50, verbose_name='назва категорії')),
                ('subtitle', models.CharField(help_text='виводиться на лендінгу в шапці. Макс. довжина 200 символів.', max_length=200, verbose_name='подзаголовок категории')),
                ('category_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='картинка категорії в шапці лендингу')),
                ('preview_category_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='маленька картинка категорії')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='опубліковано')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Наприклад, «Євро» або «Долар США».', max_length=50, verbose_name='назва валюти')),
                ('exchange', models.DecimalField(blank=True, decimal_places=2, help_text='Введіть дробове число з двома цифрами після крапки (не коми).', max_digits=5, null=True, verbose_name='курс по відношенню до гривні')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Поле автоматичне заповнюється в момент останнього збереження.', verbose_name='коли оновлювався курс')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюти',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле заповнюється автоматично і має бути унікальним.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(help_text='Максимальна довжина 100 символів', max_length=100, verbose_name='назва товару')),
                ('short_description', models.CharField(help_text='Макс. довжина 300 символів.', max_length=300, verbose_name='короткий опис товару')),
                ('description', models.TextField(verbose_name='повний опис товару')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='вартість у валюті')),
                ('new_product', models.BooleanField(blank=True, default=False, verbose_name='новинка')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='більше, ніж нинішня', verbose_name='стара ціна')),
                ('header_image', models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='головна картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 1')),
                ('image_2', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 2')),
                ('image_3', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 3')),
                ('image_4', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 4')),
                ('image_5', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 5')),
                ('image_6', models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='картинка 6')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='опубліковано')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='фірма-виробник')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категорія')),
                ('currency', models.ForeignKey(help_text='При виведенні для користувача буде автоматично перераховано в гривню.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='в якій валюті вартість')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
