# Generated by Django 3.1.3 on 2020-12-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201222_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюти'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='preview_category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='preview_category_icon',
            field=models.ImageField(help_text='Можна використовувати круглі іконки, головне, щоб для всіх категорій дотримувалася одна стилістикаМаленька картинка категорії', null=True, upload_to='images/%Y-%m-%d/', verbose_name='Маленька картинка категорії'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=0, help_text='Показується тільки для сертифікованих користувачів', max_digits=6, null=True, verbose_name='Вартість у валюті для сертифікованих'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Поле не обов\'язково для заповнення. Але, якщо воно заповнене, то в картці товару буде показана вартість для несертифікованих і незареєстрованих користувачів, а також буде можливість замовлення цього товару.', max_digits=6, null=True, verbose_name='Вартість у валюті для несертифікованих (для догляду вдома)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='Логотип бренду'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва бренду'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, help_text='Якщо категорія опублікована, то вона виводиться в списку всіх категорій на сайті. А відповідно, і її товари', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Поле заповнюється автоматично і має бути унікальним', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(help_text='Виводиться на лендінгу в шапці. Макс. довжина 200 символів', max_length=200, verbose_name='Підзаголовок категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введіть дробове число з двома цифрами після крапки (не коми)', max_digits=5, null=True, verbose_name='Курс по відношенню до гривні'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(help_text='Наприклад, «Євро» або «Долар США»', max_length=50, verbose_name='Назва валюти'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Поле автоматично заповнюється в момент останнього збереження', verbose_name='Коли оновлювався курс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Фірма-виробник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(help_text='При виведенні для користувача буде автоматично перераховано в гривню', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='В якій валюті вартість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Повний опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='Головна картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, help_text='Товар опублікований і відображається на сайті', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(help_text='Макс. довжина 300 символів', max_length=300, verbose_name='Короткий опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Поле заповнюється автоматично і має бути унікальним', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Максимальна довжина 100 символів', max_length=100, verbose_name='Назва товару'),
        ),
    ]
