# Generated by Django 3.1.3 on 2020-12-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201222_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='preview_category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='preview_category_icon',
            field=models.ImageField(help_text='Можно использовать круглые иконки, главное, чтобы для всех категорий соблюдалась одна стилистика', null=True, upload_to='images/%Y-%m-%d/', verbose_name='Маленькая картинка категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=0, help_text='Показывается только для сертифицированных пользователей', max_digits=6, null=True, verbose_name='Стоимость в валюте для сертифицированных'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Поле не обязательно для заполнения. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=6, null=True, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='Логотип бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, help_text='Если категория опубликована, то она выводится в списке всех категорий на сайте. А соответственно, и ее товары', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Поле автозаполняемо и должно быть уникально', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.CharField(help_text='Выводится на лендинге в шапке. Макс. длина 200 символов', max_length=200, verbose_name='Подзаголовок категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите дробное число с двумя цифрами после точки (не запятой)', max_digits=5, null=True, verbose_name='Курс по отношению к гривне'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(help_text='Например, "Евро" или "Доллар США"', max_length=50, verbose_name='Название валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Поле автоматически заполняется в момент последнего сохранения', verbose_name='Когда обновлялся курс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Фирма-производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(help_text='При выводе для пользователя будет автоматически пересчитано в гривну', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='В какой валюте стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Полное описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='images/shop/%Y-%m-%d/', verbose_name='Картинка 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, help_text='Товар опубликован и показывается на сайте', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(help_text='Макс. длина 300 символов', max_length=300, verbose_name='Краткое описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Поле автозаполняемо и должно быть уникально', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Максимальная длина 100 символов', max_length=100, verbose_name='Название товара'),
        ),
    ]
