# Generated by Django 3.1.3 on 2020-12-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201222_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Якщо товар не призначений для несертифікованих користувачів, залиште  значення нульовим. Але, якщо воно заповнене, то в картці товару буде показана вартість для несертифікованих і незареєстрованих користувачів, а також буде можливість замовлення цього товару', max_digits=6, verbose_name='Вартість у валюті для несертифікованих (для догляду вдома)'),
        ),
    ]
