# Generated by Django 3.1.3 on 2020-12-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201222_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Если товар не предназначен для несертифицированных пользователей, оставьте  значение нулевым. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=6, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
    ]
