# Generated by Django 3.1.3 on 2021-01-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20201223_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Наприклад: Нова пошта', max_length=50, verbose_name='Назва служби доставки')),
                ('image', models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='Логотип служби доставки')),
                ('is_published', models.BooleanField(default=True, help_text='Якщо опубліковано, спосіб доставки буде доступний користувачам при оформленні замовлення', verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Служба доставки',
                'verbose_name_plural': 'Службы доставки',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'Скасовано'), ('wait_paid', 'Очікується оплата'), ('paid', 'Оплачено'), ('sent', 'Відправлено'), ('done', 'Виконано')], max_length=30, verbose_name='Статус замовлення')),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума замовлення')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('region', models.CharField(max_length=50, verbose_name='Область')),
                ('district', models.CharField(max_length=50, verbose_name='Район')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('delivery_office', models.CharField(max_length=200, verbose_name='Адрес и номер отделения выбранной службы доставки')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформлення замовлення')),
                ('is_done', models.BooleanField(default=False, verbose_name='Виконано')),
                ('consumer', models.ForeignKey(blank=True, help_text="Якщо людина зареєстрована на сайті, буде вказано її ім'я та прізвище", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.delivery', verbose_name='Спосіб доставки')),
            ],
            options={
                'verbose_name': 'замовлення',
                'verbose_name_plural': 'замовлення',
                'ordering': ['-adding_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Наприклад: "WayForPay"', max_length=50, verbose_name='Назва способу оплати')),
                ('payment_type', models.CharField(choices=[('WFP', 'WayForPay'), ('ANY', 'Інший спосіб')], help_text="Зверніть увагу, що тільки для WayForPay буде доступна автоматична онлайн-оплата замовлення. Інші типи оплати будуть тільки виводитися на сторінці оформлення замовлення як альтернативні, і оплатити замовлення людина зможе тільки після того, як менеджер з нею зв'яжеться по телефону", max_length=30, verbose_name='Тип способу оплати')),
                ('MERCHANT_LOGIN', models.CharField(help_text="Тільки для WayForPay. Це значення ви можете отримати в ЛК WayForPay в налаштуваннях магазину у вкладці «Реквізити мерчанта».", max_length=100, verbose_name='MERCHANT LOGIN')),
                ('MERCHANT_SECRET_KEY', models.CharField(help_text="Тільки для WayForPay. Це значення ви можете отримати в ЛК WayForPay в налаштуваннях магазину у вкладці «Реквізити мерчанта».", max_length=200, verbose_name='MERCHANT SECRET KEY')),
                ('logo', models.ImageField(upload_to='images/shop/%Y-%m-%d/')),
                ('short_description', models.CharField(help_text="Короткий опис системи оплати. На сторінці сайту буде показано користувачеві, якщо даний спосіб оплати опублікований. Наприклад: «WayForPay - автоматична оплата з повною оплатою товару за допомогою картки Visa/MasterCard»", max_length=300, verbose_name='Короткий опис')),
                ('prepayment', models.PositiveSmallIntegerField(help_text='Це значення потрібно вказувати тільки для WayForPay. Значення повинно бути числом від 0 до 100. Який відсоток вкажете, такий розмір передоплати людина внесе під час автоматичної оплати після оформлення замовлення', verbose_name='Відсоток передоплати')),
                ('is_published', models.BooleanField(default=True, help_text="Якщо стоїть галочка, то даний спосіб оплати буде опублікований на сайті в момент оформлення замовлення, як альтернативний. (Без автоматичної онлайн оплати, а за погодженням, коли продавець зв'яжеться з клієнтом по телефону або e-mail)", verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Спосіб оплати',
                'verbose_name_plural': 'Способи оплати',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Набір символів довжиною до 20 знаків', max_length=20, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(help_text='Відсоток знижки, яку надає промокод. Потрібно ввести ціле число (без символу відсотка). Мінімальне значення - 0, максимальне - 100', verbose_name='Відсоток знижки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Промокод активний і діє')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='До якого замовлення відноситься')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція в замовленні',
                'verbose_name_plural': 'Позиції в замовленні',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promocode', verbose_name='Промокод'),
        ),
    ]
