# Generated by Django 3.1.3 on 2021-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210104_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='prepayment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='MERCHANT_LOGIN',
            field=models.CharField(blank=True, help_text='Тільки для WayForPay. Це значення ви можете отримати в ЛК WayForPay в налаштуваннях магазину у вкладці «Реквізити мерчанта».', max_length=100, verbose_name='MERCHANT LOGIN'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='MERCHANT_SECRET_KEY',
            field=models.CharField(blank=True, help_text='Тільки для WayForPay. Це значення ви можете отримати в ЛК WayForPay в налаштуваннях магазину у вкладці «Реквізити мерчанта».', max_length=200, verbose_name='MERCHANT SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='logo',
            field=models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='Логотип способу оплати'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='short_description',
            field=models.CharField(help_text='Короткий опис системи оплати. На сторінці сайту буде показано користувачеві, якщо даний спосіб оплати опублікований. Наприклад: «WayForPay - автоматична оплата з повною оплатою товару за допомогою картки Visa/MasterCard». Максимальна довжина 300 символів.', max_length=300, verbose_name='Короткий опис'),
        ),
    ]
