# Generated by Django 3.1.3 on 2021-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210104_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='prepayment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='MERCHANT_LOGIN',
            field=models.CharField(blank=True, help_text='Только для WayForPay. Это значение вы можете получить в ЛК WayForPay в настройках магазина во вкладке "Реквизиты мерчанта"', max_length=100, verbose_name='MERCHANT LOGIN'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='MERCHANT_SECRET_KEY',
            field=models.CharField(blank=True, help_text='Только для WayForPay. Это значение вы можете получить в ЛК WayForPay в настройках магазина во вкладке "Реквизиты мерчанта"', max_length=200, verbose_name='MERCHANT SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='logo',
            field=models.ImageField(upload_to='images/shop/%Y-%m-%d/', verbose_name='Логотип способа оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='short_description',
            field=models.CharField(help_text='Краткое описание системы оплаты. На странице сайта будет показано пользователю, если данный способ оплаты опубликован. Например: "WayForPay - автоматическая оплата с полной оплатой товара с помощью карты Visa/MasterCard". Максимальная длина 300 символов', max_length=300, verbose_name='Краткое описание'),
        ),
    ]
