# Generated by Django 3.1.3 on 2021-01-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_reference',
            field=models.CharField(max_length=30, null=True, verbose_name='Уникальный номер заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если стоит галочка, то данный способ оплаты будет опубликован на сайте в момент оформления заказа', verbose_name='Опубликовано'),
        ),
    ]
