# Generated by Django 3.1.3 on 2021-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210112_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_order_date',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата для WFP'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость высчитывается исходя из того, заказывал сертифицированный пользователь или нет', max_digits=6, null=True, verbose_name='По какой стоимости в гривне был куплен товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=2, help_text='Показывается только для сертифицированных пользователей', max_digits=6, null=True, verbose_name='Стоимость в валюте для сертифицированных'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Если товар не предназначен для несертифицированных пользователей, оставьте  значение нулевым. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=6, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
    ]
