# Generated by Django 3.1.3 on 2021-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210112_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_order_date',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата для WFP'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Вартість розраховується виходячи з того, чи замовляв сертифікований користувач чи ні', max_digits=6, null=True, verbose_name='За якою вартістю в гривні був куплений товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=2, help_text='Показується тільки для сертифікованих користувачів', max_digits=6, null=True, verbose_name='Вартість у валюті для сертифікованих'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Якщо товар не призначений для несертифікованих користувачів, залиште  значення нульовим. Але, якщо воно заповнене, то в картці товару буде показана вартість для несертифікованих і незареєстрованих користувачів, а також буде можливість замовлення цього товару', max_digits=6, verbose_name='Вартість у валюті для несертифікованих (для догляду вдома)'),
        ),
    ]
