# Generated by Django 3.1.3 on 2021-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210113_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant_order_date',
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_certified',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Нова знижена вартість показується тільки сертифікованим користувачам. Якщо нова вартість зі знижкою не передбачена, залиште значення нульовим. Якщо поле заповнене, буде показана нова знижена вартість, і за нею сертифікований косметолог буде купувати товар', max_digits=7, null=True, verbose_name='Нова знижена вартість у валюті для сертифікованих користувачів'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_guest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Якщо для несертифікованих користувачів по цьому товару не передбачена нова знижка, залиште значення нульовим', max_digits=7, null=True, verbose_name='Нова знижена вартість у валюті для несертифікованих (для домашнього догляду)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Введіть ціле число', verbose_name='Обсяг продукції в мілілітрах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(null=True, to='shop.Product', verbose_name='На які продукти поширюється промокод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=2, help_text='Показується тільки сертифікованим користувачам', max_digits=7, null=True, verbose_name='Вартість у валюті для сертифікованих користувачів'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Якщо товар не призначений для несертифікованих користувачів, залиште  значення нульовим. Але, якщо воно заповнене, то в картці товару буде показана вартість для несертифікованих і незареєстрованих користувачів, а також буде можливість замовлення цього товару', max_digits=7, verbose_name='Вартість у валюті для несертифікованих (для догляду вдома)'),
        ),
    ]
