# Generated by Django 3.1.3 on 2021-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210113_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant_order_date',
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_certified',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Новая скидочная стоимость показывается только сертифицированным пользователям. Если новая стоимость по скидке не предусмотрена, оставьте значение нулевым. Если поле заполнено, будет показана новая скидочная стоимость, и по ней сертифицированный косметолог будет приобретать товар', max_digits=7, null=True, verbose_name='Новая скидочная стоимость в валюте для сертифицированных пользователей'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price_guest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Если для несертифицированных пользователей по этому товару не предусмотрена новая скидочная стоимость, оставьте значение нулевым', max_digits=7, null=True, verbose_name='Новая скидочная стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Введите целое число', verbose_name='Объем продукции в миллилитрах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(null=True, to='shop.Product', verbose_name='На какие продукты распространяется промокод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_certified',
            field=models.DecimalField(decimal_places=2, help_text='Показывается только сертифицированным пользователям', max_digits=7, null=True, verbose_name='Стоимость в валюте для сертифицированных пользователей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Если товар не предназначен для несертифицированных пользователей, оставьте  значение нулевым. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=7, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
    ]
