# Generated by Django 3.1.3 on 2021-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210216_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(to='shop.Product', verbose_name='На какие продукты распространяется промокод'),
        ),
    ]
