# Generated by Django 3.1.3 on 2021-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210216_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price_certified',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Новая скидочная стоимость показывается только сертифицированным пользователям. Если новая стоимость по скидке не предусмотрена, оставьте значение нулевым. Если поле заполнено, будет показана новая скидочная стоимость, и по ней сертифицированный косметолог будет приобретать товар', max_digits=7, null=True, verbose_name='Новая скидочная стоимость в валюте для сертифицированных пользователей'),
        ),
    ]
