# Generated by Django 3.1.3 on 2021-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210216_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price_certified',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Нова знижена вартість показується тільки сертифікованим користувачам. Якщо нова вартість зі знижкою не передбачена, залиште значення нульовим. Якщо поле заповнене, буде показана нова знижена вартість, і за нею сертифікований косметолог буде купувати товар.', max_digits=7, null=True, verbose_name='Нова знижена вартість у валюті для сертифікованих користувачів'),
        ),
    ]
