# Generated by Django 3.1.3 on 2021-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210216_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Если товар не предназначен для несертифицированных пользователей, оставьте  значение нулевым. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=7, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
    ]
