# Generated by Django 3.1.3 on 2021-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210216_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price_certified',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Новая скидочная стоимость показывается только сертифицированным пользователям. Если новая стоимость по скидке не предусмотрена, оставьте значение нулевым. Если поле заполнено, будет показана новая скидочная стоимость, и по ней сертифицированный косметолог будет приобретать товар', max_digits=7, null=True, verbose_name='Новая скидочная стоимость в валюте для сертифицированных пользователей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Если для несертифицированных пользователей по этому товару не предусмотрена новая скидочная стоимость, оставьте значение нулевым', max_digits=7, null=True, verbose_name='Новая скидочная стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_guest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Если товар не предназначен для несертифицированных пользователей, оставьте  значение нулевым. Но, если оно заполнено, то в карточке товара будет показана стоимость для несертифицированных и незарегистрированных пользователей, а также будет возможность заказа этого товара', max_digits=7, verbose_name='Стоимость в валюте для несертифицированных (для домашнего ухода)'),
        ),
    ]
