# Generated by Django 3.1.3 on 2021-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210216_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(blank=True, help_text='Введите целое число', verbose_name='Объем продукции в миллилитрах'),
        ),
    ]
