# Generated by Django 3.1.3 on 2020-12-16 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Поле автозаполняемо. Должно быть уникально.', unique=True, verbose_name='слаг')),
                ('title', models.CharField(help_text='Название вебинара. Служит заголовком на лендинге. Если вебинары по этой теме уже проводились, желательно, чтобы было в едином стиле с предыдущими. Макс. длина 200 символов.', max_length=200, verbose_name='название вебинара')),
                ('subtitle', models.CharField(help_text='Макс. длина 250 символов.', max_length=250, verbose_name='подзаголовок')),
                ('header_image', models.ImageField(help_text='Главное изображение, которое выводится в шапке лендинга.', upload_to='workshops/%Y-%m-%d/', verbose_name='главное изображение')),
                ('starting_date', models.DateField(help_text='Дата начала вебинара', verbose_name='дата начала')),
                ('description', models.TextField(verbose_name='описание вебинара')),
                ('description_image', models.ImageField(upload_to='workshops/%Y-%m-%d/', verbose_name='картинка к описанию')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован на сайте')),
                ('is_started', models.BooleanField(default=False, help_text='Если начат, желательно снять галочку с "Опубликован на сайте", чтобы во время его проведения вебинар не показывался на сайте, а люди не могли записаться.', verbose_name='вебинар начат')),
                ('students', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='участники вебинара')),
            ],
            options={
                'verbose_name': 'вебинар',
                'verbose_name_plural': 'вебинары',
                'ordering': ['starting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Макс. длина 150 символов.', max_length=150, verbose_name='название темы')),
                ('short_description', models.CharField(help_text='Макс. длина 200 символов.', max_length=200, verbose_name='краткое описание темы')),
                ('is_published', models.BooleanField(default=True, help_text='Тема показана на лендинге вебинара и в кабинете пользователя.', verbose_name='опубликовано')),
                ('webinar', models.ForeignKey(help_text='К какому вебинару относится тема.', on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar', verbose_name='семинар')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Развание варианта участия. Макс. длина 150 символов.', max_length=150, verbose_name='название')),
                ('description', models.CharField(help_text='Макс. длина 300 символов.', max_length=300, verbose_name='описание варианта участия')),
                ('is_paid', models.BooleanField(default=False, help_text='Если это платный вариант участия, поставьте галочку, чтобы была подключена возможность оплаты.', verbose_name='Платный вариант участия')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Если вверху вы указали галочкой, что вебинар платный, введите целое число стоимости без дробной части.', max_digits=5, verbose_name='стоимость варианта участия')),
                ('webinar', models.ForeignKey(help_text='К какому вебинару относится.', on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar', verbose_name='вебинар')),
            ],
            options={
                'verbose_name': 'вариант участия',
                'verbose_name_plural': 'варианты участия',
            },
        ),
    ]
