# Generated by Django 3.1.3 on 2020-12-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='starting_date',
            field=models.DateTimeField(help_text='Дата и время начала вебинара', verbose_name='дата и время начала'),
        ),
    ]
