# Generated by Django 3.1.3 on 2020-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_auto_20201216_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Если вверху вы указали галочкой, что вебинар платный, введите целое число стоимости без дробной части.', max_digits=5, null=True, verbose_name='стоимость варианта участия'),
        ),
    ]
