# Generated by Django 3.1.3 on 2021-02-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webinars', '0004_auto_20210214_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='students',
        ),
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('free', 'Бесплатное участие'), ('only_watch', 'Оплата только за участие'), ('materials', 'С закупкой материалов')], max_length=100, null=True, verbose_name='тип варианта участия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(help_text='Макс. длина 300 символов', max_length=300, verbose_name='описание варианта участия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Если вверху вы указали галочкой, что вебинар платный, введите целое число стоимости без дробной части', max_digits=5, null=True, verbose_name='стоимость варианта участия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(help_text='Развание варианта участия. Макс. длина 150 символов', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='option',
            name='webinar',
            field=models.ForeignKey(help_text='К какому вебинару относится', on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar', verbose_name='вебинар'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Тема показана на лендинге вебинара и в кабинете пользователя', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='short_description',
            field=models.CharField(help_text='Макс. длина 200 символов', max_length=200, verbose_name='краткое описание темы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(help_text='Макс. длина 150 символов', max_length=150, verbose_name='название темы'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='webinar',
            field=models.ForeignKey(help_text='К какому вебинару относится тема', on_delete=django.db.models.deletion.CASCADE, to='webinars.webinar', verbose_name='вебинар'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='header_image',
            field=models.ImageField(help_text='Главное изображение, которое выводится в шапке лендинга', upload_to='workshops/%Y-%m-%d/', verbose_name='главное изображение'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='is_started',
            field=models.BooleanField(default=False, help_text='Если начат, желательно снять галочку с "Опубликован на сайте", чтобы во время его проведения вебинар не показывался на сайте, а люди не могли записаться', verbose_name='вебинар начат'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(help_text='Поле автозаполняемо. Должно быть уникально', unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='subtitle',
            field=models.CharField(help_text='Макс. длина 250 символов', max_length=250, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(help_text='Название вебинара. Служит заголовком на лендинге. Если вебинары по этой теме уже проводились, желательно, чтобы было в едином стиле с предыдущими. Макс. длина 200 символов', max_length=200, verbose_name='название вебинара'),
        ),
        migrations.CreateModel(
            name='WebinarPromocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Набор символов длиной до 20 знаков', max_length=20, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(help_text='Процент скидки, которую предоставляет промокод. Нужно ввести целое число (без символа процента). Минимальное значение - 0, максимальное - 100', verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Промокод активен и действует')),
                ('webinars', models.ManyToManyField(to='webinars.Webinar', verbose_name='На какие вебинары распространяется промокод')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='WebinarOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'Отменен'), ('apply', 'Принят'), ('paid', 'Оплачен')], max_length=30, verbose_name='Статус заказа')),
                ('order_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Сумма покупки')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления записи')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webinars.option', verbose_name='Выбранный вариант участия')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webinars.webinarpromocode', verbose_name='Промокод')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('webinar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webinars.webinar', verbose_name='На какой вебинар была запись')),
            ],
            options={
                'verbose_name': 'заявка на участие',
                'verbose_name_plural': 'заявки на участие',
                'ordering': ['-id'],
            },
        ),
    ]
