# Generated by Django 3.1.3 on 2021-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0006_option_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='order_reference',
        ),
        migrations.AddField(
            model_name='webinarorder',
            name='order_reference',
            field=models.CharField(max_length=30, null=True, verbose_name='Уникальный номер заказа'),
        ),
    ]
